### PR TITLE
Bugfix proposal to issue #12

### PR DESCRIPTION
**Pull request by demogog**

### CODE REVIEW

**Comment by demogog** [comment]
@nothingalike Hi. Here's the pull request regarding the issue #12 

Best regards, 
Alex

**Comment by nothingalike** [comment]
@demogog can you provide a sample transaction hash that can prove this is the correct fix. I checked the documentation and I'm not sure this is a correct fix. Just need a little help verifying. 

This is what I reviewed to verify domain/model structure
https://api.koios.rest/#post-/tx_info

**Comment by nothingalike** [comment]
Ignore previous request. i forgot you had an example on the issue

**Review by nothingalike — APPROVED** [review]

**Comment by nothingalike** [comment]
@demogog thank you for contributing!

**Pull request merged**
